name: Dmitry's blog
description: Science of programming
meta_description: "Dmitry Olshansky blog on programming"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: '/'
domain_name: 'http://olshansky.me'
google_analytics: 'UA-101003587-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://olshansky.me'
author:         'Dmitry Olshansky'

